config/routes.rb
IncidentReporter::Application.routes.draw do
  devise_for :users

  resources :incident_reports

  root :to => "incident_reports#index"

end

app/models/incident_report.rb
class IncidentReport < ActiveRecord::Base
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/incident_reports_controller.rb
class IncidentReportsController < ApplicationController
  before_filter :authenticate_user!, :except => [:new, :index]
  
  # GET /incident_reports
  # GET /incident_reports.xml
  def index
    @incident_reports = IncidentReport.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @incident_reports }
    end
  end

  # GET /incident_reports/1
  # GET /incident_reports/1.xml
  def show
    @incident_report = IncidentReport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @incident_report }
    end
  end

  # GET /incident_reports/new
  # GET /incident_reports/new.xml
  def new
    @incident_report = IncidentReport.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @incident_report }
    end
  end

  # GET /incident_reports/1/edit
  def edit
    @incident_report = IncidentReport.find(params[:id])
  end

  # POST /incident_reports
  # POST /incident_reports.xml
  def create
    @incident_report = IncidentReport.new(params[:incident_report])

    respond_to do |format|
      if @incident_report.save
        format.html { redirect_to(@incident_report, :notice => 'Incident report was successfully created.') }
        format.xml  { render :xml => @incident_report, :status => :created, :location => @incident_report }
        link = "#{request.protocol}#{request.host_with_port}" + incident_report_path(@incident_report)
        UserMailer.incident_received(@incident_report, link).deliver
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @incident_report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /incident_reports/1
  # PUT /incident_reports/1.xml
  def update
    @incident_report = IncidentReport.find(params[:id])

    respond_to do |format|
      if @incident_report.update_attributes(params[:incident_report])
        format.html { redirect_to(@incident_report, :notice => 'Incident report was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @incident_report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /incident_reports/1
  # DELETE /incident_reports/1.xml
  def destroy
    @incident_report = IncidentReport.find(params[:id])
    @incident_report.destroy

    respond_to do |format|
      format.html { redirect_to(incident_reports_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incident_reports_helper.rb
module IncidentReportsHelper
end

app/views/incident_reports/_form.html.erb
<%= form_for(@incident_report) do |f| %>
  <% if @incident_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incident_report.errors.count, "error") %> prohibited this incident_report from being saved:</h2>

      <ul>
      <% @incident_report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :incident_occurred_at %><br />
    <%= f.text_field :incident_occurred_at %>
  </div>
  <div class="field">
    <%= f.label :incident_location %><br />
    <%= f.text_field :incident_location %>
  </div>
  <div class="field">
    <%= f.label :incident_description %><br />
    <%= f.text_area :incident_description %>
  </div>
  <div class="field">
    <%= f.label :incident_location_description %><br />
    <%= f.text_area :incident_location_description %>
  </div>
  <div class="field">
    <%= f.label :other_party_is_tns_employee %><br />
    <%= f.check_box :other_party_is_tns_employee %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incident_reports/edit.html.erb
<h1>Editing incident_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @incident_report %> |
<%= link_to 'Back', incident_reports_path %>

app/views/incident_reports/index.html.erb
<h1>Listing incident_reports</h1>

<div class="clean-table">
<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Incident occurred at</th>
    <th>Incident location</th>
    <th>Incident description</th>
    <th>Incident location description</th>
    <th>Other party is tns employee</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @incident_reports.each do |incident_report| %>
  <tr>
    <td><%= incident_report.name %></td>
    <td><%= incident_report.phone %></td>
    <td><%= incident_report.incident_occurred_at.strftime("%-m-%-d-%Y") rescue nil %></td>
    <td><%= incident_report.incident_location %></td>
    <td><%= incident_report.incident_description %></td>
    <td><%= incident_report.incident_location_description %></td>
    <td><%= incident_report.other_party_is_tns_employee %></td>
    <td><%= link_to 'Show', incident_report %></td>
    <td><%= link_to 'Edit', edit_incident_report_path(incident_report) %></td>
    <td><%= link_to 'Destroy', incident_report, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>

</table>
</div>
<br />

<%= link_to 'New Incident report', new_incident_report_path %>

app/views/incident_reports/new.html.erb
<h1>New incident_report</h1>

<%= render 'form' %>

<%= link_to 'Back', incident_reports_path %>

app/views/incident_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @incident_report.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @incident_report.phone %>
</p>

<p>
  <b>Incident occurred at:</b>
  <%= @incident_report.incident_occurred_at.strftime("%-m-%-d-%Y") rescue nil %>
</p>

<p>
  <b>Incident location:</b>
  <%= @incident_report.incident_location %>
</p>

<p>
  <b>Incident description:</b>
  <%= @incident_report.incident_description %>
</p>

<p>
  <b>Incident location description:</b>
  <%= @incident_report.incident_location_description %>
</p>

<p>
  <b>Other party is tns employee:</b>
  <%= @incident_report.other_party_is_tns_employee %>
</p>


<%= link_to 'Edit', edit_incident_report_path(@incident_report) %> |
<%= link_to 'Back', incident_reports_path %>

app/views/layouts/application.html.erb
<!doctype html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ --> 
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <%- # Always force latest IE rendering engine (even in intranet) & Chrome Frame -%>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title></title>
  <meta name="description" content="">
  <meta name="author" content="">

  <%- # Mobile viewport optimized: j.mp/bplateviewport -%>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%- # Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -%>
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">

  <%- # CSS : implied media="all" -%>
  <%= stylesheet_link_tag 'application' %>

  <%- # Uncomment if you are specifically targeting less enabled mobile browsers -%>
  <%#= stylesheet_link_tag "handheld", :media => "handheld" %>
 
  <%= csrf_meta_tag %>
 
  <%- # All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects -%>
  <%= javascript_include_tag 'modernizr-1.6.min.js' %>

</head>
<body>

  <div id="container">
    <header>

    </header>
    
    <div id="main">
      <%= yield %>
    </div>
    
    <footer>

    </footer>
  </div> <!--! end of #container -->

  <%- # Javascript at the bottom for fast page loading -%>

  <%- # Grab Google CDN's jQuery. fall back to local if necessary -%>
  <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.js' %>
  <%= javascript_tag %{!window.jQuery && document.write(unescape('%3Cscript src="/javascripts/jquery-1.4.3.min.js"%3E%3C/script%3E'))} %>

  <%= javascript_include_tag 'plugins' %>
  <%= javascript_include_tag :defaults %>

  <%- # Fix any <img> or .png_bg background-images -%>
  <!--[if lt IE 7 ]>
    <%= javascript_include_tag 'dd_belatedpng.js' %>
    <%= javascript_tag %{DD_belatedPNG.fix('img, .png_bg')} %>
  <![endif]-->

  <%- # yui profiler and profileviewer - except for production -%>
  <%= javascript_include_tag 'profiling/yahoo-profiling.min.js', 'profiling/config.js' unless Rails.env.production? %>

  <%- # asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet -%>
  <%- # change the UA-XXXXX-X to be your site's ID -%>
  <%- if Rails.env.production? -%>
  <script>
   var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
   (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
   })(document, 'script');
  </script>
  <%- end -%>

</body>
</html>